export interface Task {
  id?: string;               // Optional: Generated by the API
  name: string;              // Required: Task name
  completed: boolean;        // Required: Task completion status
  dueDate: string;           // Required: Due date in YYYY-MM-DD format
  dueTime?: string;          // Optional: Due time in HH:MM format
  priority: 'high' | 'medium' | 'low';  // Required: Task priority
  description?: string;      // Optional: Task description
  userId?: string;           // Optional: User ID, set by the API
  createdAt?: number;        // Optional: Creation timestamp, set by the service 
  updatedAt?: number;        // Optional: Last update timestamp, set by the service
  icon?: string;             // Optional: Icon class for the task
} 